create table if not exists preguntas_pendientes (
  id bigint generated by default as identity primary key,
  pregunta_id text unique,
  item_id text,
  pregunta text,
  motivo text,
  cuenta_numero text,
  cuenta_nombre text,
  resuelta boolean default false,
  created_at timestamptz default now()
);
alter table preguntas_pendientes enable row level security;
create policy "allow all" on preguntas_pendientes for all using (true) with check (true);
